var getDomain = require('./../src/index.js').getDomain;

var request = require('request').request;

var urls = ['1plus1tv.ru',
	'filmitorrent.org',
	'kivvi.kz',
	'ria.ru',
	'univertv.org',
	'58.com',
	'formyip.com',
	'lol24.ee',
	'rt.com',
	'video9.in',
	'adme.ru',
	'fullmovies.net.in',
	'mail.ru',
	'russia.tv',
	'video-dom2.ru',
	'baskino.com',
	'funnymasti.com',
	'megogo.net',
	'rutube.ru',
	'videomore.ru',
	'bhaskar.com',
	'funnyordie.com',
	'merinews.com',
	'seasonvar.ru',
	'videoup.net',
	'bigcinema.tv',
	'gidonline.club',
	'metacafe.com',
	'smotrisport.tv',
	'vimeo.com',
	'bigmir.net',
	'hdkinomax.com',
	'mobango.com',
	'sovsport.ru',
	'vuclip.com',
	'bobfilm.net',
	'hotbhojpuri.in',
	'mobfilmz.com',
	'sportbox.ru',
	'weather.com.cn',
	'break.com',
	'in.com',
	'mobkino.org',
	'sport-express.ru',
	'whatsappmasti.com',
	'bugaga.ru',
	'iplt20.com',
	'mp4mobilemovies.net',
	'starsports.com',
	'wikia.com',
	'carambatv.ru',
	'ivi.ru',
	'my-hit.org',
	'test-clean.com',
	'yourepeat.com',
	'championat.com',
	'killboring.in',
	'ntv.ru',
	'test.com',
	'youtube.com',
	'concretejungle.ru',
	'kinobar.net',
	'o2cinemas.com',
	'tfilm.me',
	'zeemarathi.com',
	'dailymotion.com',
	'kinogo.co',
	'onlinemoviewatchs.com',
	'tnt-online.ru',
	'zeetv.com',
	'dailytube.in',
	'kinogo.net',
	'onlinemultfilmy.ru',
	'trendingwoman.com',
	'zerx.co',
	'desinema.com',
	'kinokrad.net',
	'pagalworld.com',
	'turkcinema.tv',
	'zoomby.ru',
	'dom2.ru',
	'kinopati.ru',
	'pinguda.com',
	'tushkan.net',
	'dream-film.net',
	'kinopoisk.ru',
	'playground.ru',
	'tvzvezda.ru'
];

for (u in urls) {
	console.log(urls[u]);
	console.log(getDomain('front.' + urls[u] + '/end'));
	console.log('================');
}

var myurl = 'm.net.com/hehe';
console.log(getDomain(myurl));